server:
   port: 8082
spring:
   application:
      name: random-animal

eureka:
   client:
      service-url:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
   instance:
      preferIpAddress: true